featureMatrix = [];
labels = [];


fileList = {
    'U01_Acc_FreqD_FDay.mat', 'U01_Acc_FreqD_MDay.mat', ...
    'U01_Acc_TimeD_FDay.mat', 'U01_Acc_TimeD_FreqD_FDay.mat', ...
    'U01_Acc_TimeD_FreqD_MDay.mat', 'U01_Acc_TimeD_MDay.mat', ... 
    'U02_Acc_FreqD_FDay.mat', 'U02_Acc_FreqD_MDay.mat', ...
    'U02_Acc_TimeD_FDay.mat', 'U02_Acc_TimeD_FreqD_FDay.mat', ...
    'U02_Acc_TimeD_FreqD_MDay.mat', 'U02_Acc_TimeD_MDay.mat', ...
    'U03_Acc_FreqD_FDay.mat', 'U03_Acc_FreqD_MDay.mat', ...
    'U03_Acc_TimeD_FDay.mat', 'U03_Acc_TimeD_FreqD_FDay.mat', ...
    'U03_Acc_TimeD_FreqD_MDay.mat', 'U03_Acc_TimeD_MDay.mat', ...
    'U04_Acc_FreqD_FDay.mat', 'U04_Acc_FreqD_MDay.mat', ...
    'U04_Acc_TimeD_FDay.mat', 'U04_Acc_TimeD_FreqD_FDay.mat', ...
    'U04_Acc_TimeD_FreqD_MDay.mat', 'U04_Acc_TimeD_MDay.mat', ...
    'U05_Acc_FreqD_FDay.mat', 'U05_Acc_FreqD_MDay.mat', ...
    'U05_Acc_TimeD_FDay.mat', 'U05_Acc_TimeD_FreqD_FDay.mat', ...
    'U05_Acc_TimeD_FreqD_MDay.mat', 'U05_Acc_TimeD_MDay.mat', ...
    'U06_Acc_FreqD_FDay.mat', 'U06_Acc_FreqD_MDay.mat', ...
    'U06_Acc_TimeD_FDay.mat', 'U06_Acc_TimeD_FreqD_FDay.mat', ...
    'U06_Acc_TimeD_FreqD_MDay.mat', 'U06_Acc_TimeD_MDay.mat', ...
    'U07_Acc_FreqD_FDay.mat', 'U07_Acc_FreqD_MDay.mat', ...
    'U07_Acc_TimeD_FDay.mat', 'U07_Acc_TimeD_FreqD_FDay.mat', ...
    'U07_Acc_TimeD_FreqD_MDay.mat', 'U07_Acc_TimeD_MDay.mat', ...
    'U08_Acc_FreqD_FDay.mat', 'U08_Acc_FreqD_MDay.mat', ...
    'U08_Acc_TimeD_FDay.mat', 'U08_Acc_TimeD_FreqD_FDay.mat', ...
    'U08_Acc_TimeD_FreqD_MDay.mat', 'U08_Acc_TimeD_MDay.mat', ...
    'U09_Acc_FreqD_FDay.mat', 'U09_Acc_FreqD_MDay.mat', ...
    'U09_Acc_TimeD_FDay.mat', 'U09_Acc_TimeD_FreqD_FDay.mat', ...
    'U09_Acc_TimeD_FreqD_MDay.mat', 'U09_Acc_TimeD_MDay.mat', ...
    'U10_Acc_FreqD_FDay.mat', 'U10_Acc_FreqD_MDay.mat', ...
    'U10_Acc_TimeD_FDay.mat', 'U10_Acc_TimeD_FreqD_FDay.mat', ...
    'U10_Acc_TimeD_FreqD_MDay.mat', 'U10_Acc_TimeD_MDay.mat', ...
};

% User IDs corresponding to files
userLabels = [
    1, 1, 1, 1, 1, 1, ...
    2, 2, 2, 2, 2, 2, ...
    3, 3, 3, 3, 3, 3, ...
    4, 4, 4, 4, 4, 4, ...
    5, 5, 5, 5, 5, 5, ...
    6, 6, 6, 6, 6, 6, ...
    7, 7, 7, 7, 7, 7, ...
    8, 8, 8, 8, 8, 8, ...
    9, 9, 9, 9, 9, 9, ...
    10, 10, 10, 10, 10, 10
];

maxColumns = 0;
for i = 1:length(fileList)
    data = load(fileList{i});
    featureKey = fieldnames(data);
    featureData = data.(featureKey{1});
    maxColumns = max(maxColumns, size(featureData, 2));
end

for i = 1:length(fileList)
    % Load the .mat file
    data = load(fileList{i});
    featureKey = fieldnames(data);
    featureData = data.(featureKey{1});

    paddedData = [featureData, zeros(size(featureData, 1), maxColumns - size(featureData, 2))];

    featureMatrix = [featureMatrix; paddedData];
    labels = [labels; repmat(userLabels(i), size(featureData, 1), 1)];
end

save('combinedFeatures.mat', 'featureMatrix', 'labels');

normalizedFeatures = normalize(featureMatrix, 'range', [0, 1]);
save('normalizedFeatures.mat', 'normalizedFeatures', 'labels');

meanValues = mean(normalizedFeatures);
stdValues = std(normalizedFeatures);
variance = var(normalizedFeatures);

uniqueUsers = unique(labels);
interUserVariance = zeros(size(normalizedFeatures, 2), 1);

for i = 1:length(uniqueUsers)
    userSamples = normalizedFeatures(labels == uniqueUsers(i), :);
    interUserVariance = interUserVariance + var(userSamples, 0, 1);
end
interUserVariance = interUserVariance / length(uniqueUsers);

intraUserVariance = zeros(min(10, length(uniqueUsers)), 1);
for i = 1:min(length(uniqueUsers), 10)
    userSamples = normalizedFeatures(labels == uniqueUsers(i), :);
    intraUserVariance(i) = mean(var(userSamples, 0, 1));
end
save('dataStatistics.mat', 'meanValues', 'stdValues', 'variance', 'interUserVariance', 'intraUserVariance');

figure;
bar([meanValues', stdValues', variance']);
title('Feature-Wise Descriptive Statistics');
xlabel('Features');
ylabel('Values');
legend({'Mean', 'Standard Deviation', 'Variance'}, 'Location', 'NorthWest');
grid on;
saveas(gcf, 'Descriptive_Statistics.png');

figure;
bar([mean(interUserVariance), mean(intraUserVariance)]);
title('Comparison of Inter-User and Intra-User Variance');
xlabel('Variance Type');
ylabel('Average Variance');
xticks([1 2]);
xticklabels({'Inter-User Variance', 'Intra-User Variance'});
grid on;
saveas(gcf, 'Inter_Intra_User_Variance_Comparison.png');
